### ISSUE TITLE
Application language depending on the server

### ISSUE THREAD

**Issue by MeDustyy** [AlexisL61/JackboxUtility#133]
Add the ability for each server to change the language of the application.

For example, when selecting a Ukrainian server, the Ukrainian language of the application is automatically selected, regardless of the system language.

**Comment by AlexisL61** [comment]
I agree with this change, there will just be one problem with the future English server. If the app is translated into a language without a server, and the user is using the English server, he should see the app in his language and not in English.

**Comment by AkiraArtuhaxis** [comment]
This can be fixed by making the program select everything accordingly.
If the server is English, it'd just be Select server → Select app language based on the OS (English if it's not supported currently)
If the server isn't English (French, German, Spanish and Ukrainian), the app language would always be the one that's predetermined by that server.
However, if let's say a German user wants to use the English server for some reason, it should always select the English language by default, just so the app is not half English and half German.
