### ISSUE TITLE
Fast launcher

### ISSUE THREAD

**Issue by AlexisL61** [AlexisL61/JackboxUtility#14]
## Description

A user should be able to launch a specific game.
The fast launcher actually uses a system where a .swf file is replaced. For steam, it should use the “launchto” parameter.
The use of the parameter brings one problem : Steam wants the user to confirm the game will launch with the parameters.
There seems to be a way to remove the confirmation when calling : \<steampath\>/steam.exe --appid \<id\> --launchto ...

## TODO

- [ ] Try to use the command manually
- [ ] Integrate the command in the app

**Comment by AkiraArtuhaxis** [comment]
At the moment, there are some things that need improvement from the Fast launcher part:
- Games from Packs 1-4 open fast, but they need an Enter press on the title screen. This is not the case on newer Packs, so this should be the same here.
- Lie Swatter, although it skips the intro, boots to the Party Pack menu and needs to be selected there. This is because if the fast method is used to boot into Lie Swatter, the game softlocks after the "ROUND 1" jingle plays. No fix is known at the moment.
- On Steam, in Packs 2, 5-9 and the Starter, the games can load even faster by skipping the Party Pack sequence entirely, using the "launchTo" method. CMD is used to bypass the confirmation when calling that. These Packs should still use the old fast method for EGS users.
